---
version: "3"

dotenv:
  - ".env"

interval: 500ms

tasks:
  i:
    desc: download dependencies and verify integrity
    cmds:
      - go mod download
      - go mod verify

  tidy:
    desc: runs go mod tidy
    cmds:
      - go mod tidy

  build:
    desc: builds the project
    cmds:
      - cd cmd/media-docker-server && go build -o ../../dist/server-main main.go
      - cd cmd/media-docker-client && go build -o ../../dist/client-main main.go

  client:
    desc: run client main.go file
    cmds:
      - go run cmd/media-docker-client/main.go

  server:
    desc: run server main.go file
    cmds:
      - go run cmd/media-docker-server/main.go
