/*
    NOTE: do not edit this file just copy paste to your project.
    this file contains file uploading logic to Media-Docker.
*/

import * as fs from "fs/promises";

// only valid files will be allowed to upload
const validFiles = {
  image: ["jpeg", "jpg", "png"],
  video: ["mp4", "webm", "ogg", "mkv"],
  audio: ["mp3", "mpeg", "wav"],
};

type Result<T> = { message: string; data: T };

class MediaDocker {
  // main fucntion for uploading file to media-docker server
  private async uploadFileToMediaDockerServer<T>(
    serverKey: string,
    serverBaseURL: string,
    filePath: string,
    apiEndPoint: string
  ): Promise<Result<T>> {
    // file extension
    let fileType = filePath.split(".").pop();
    const ext = fileType;
    if (!fileType) {
      throw new Error("invalid file type");
    } else if (validFiles.audio.includes(fileType)) {
      fileType = "audio";
    } else if (validFiles.image.includes(fileType)) {
      fileType = "image";
    } else if (validFiles.video.includes(fileType)) {
      fileType = "video";
    } else {
      throw new Error("invalid file type");
    }

    const content = await fs.readFile(filePath);

    const formData = new FormData();
    formData.append(fileType + "File", new Blob([content], { type: `${fileType}/${ext}` }));

    const response = await fetch(serverBaseURL + `/api/v1/uploads/${apiEndPoint}`, {
      method: "POST",
      body: formData as FormData,
      headers: {
        Authorization: serverKey,
      },
    });

    const resData = await response.json();
    if (response.status !== 201) {
      throw new Error("message" in resData ? resData.message : "unknown");
    }

    return resData;
  }

  async uploadVideo(serverKey: string, serverBaseURL: string, filePath: string): Promise<string> {
    const res = await this.uploadFileToMediaDockerServer<{ fileUrl: string }>(
      serverKey,
      serverBaseURL,
      filePath,
      "video"
    );
    return res.data.fileUrl;
  }
  async uploadVideoResolutions(
    serverKey: string,
    serverBaseURL: string,
    filePath: string
  ): Promise<{
    "360": string;
    "480": string;
    "720": string;
    "1080": string;
  }> {
    const res = await this.uploadFileToMediaDockerServer<{
      "360": string;
      "480": string;
      "720": string;
      "1080": string;
    }>(serverKey, serverBaseURL, filePath, "videoResolutions");
    return res.data;
  }
  async uploadImage(serverKey: string, serverBaseURL: string, filePath: string): Promise<string> {
    const res = await this.uploadFileToMediaDockerServer<{ fileUrl: string }>(
      serverKey,
      serverBaseURL,
      filePath,
      "image"
    );
    return res.data.fileUrl;
  }
  async uploadAudio(serverKey: string, serverBaseURL: string, filePath: string): Promise<string> {
    const res = await this.uploadFileToMediaDockerServer<{ fileUrl: string }>(
      serverKey,
      serverBaseURL,
      filePath,
      "audio"
    );
    return res.data.fileUrl;
  }
  async deleteFile(
    serverKey: string,
    serverBaseURL: string,
    id: string,
    type: "image" | "video" | "audio"
  ): Promise<boolean> {
    const response = await fetch(serverBaseURL + "/api/v1/destroys/deleteFile", {
      method: "DELETE",
      body: JSON.stringify({ id: id, type: type }),
      headers: {
        Authorization: serverKey,
        "Content-Type": "application/json",
      },
    });

    if (response.status === 200) {
      return true;
    }

    const resData: { message: string } = await response.json();
    throw new Error(resData.message);
  }
}

const mediaDocker = new MediaDocker();
export default mediaDocker;
